//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvatarBot.Bot.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringsFR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsFR() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AvatarBot.Bot.Properties.StringsFR", typeof(StringsFR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Personnages :.
        /// </summary>
        internal static string allcharacters_header {
            get {
                return ResourceManager.GetString("allcharacters_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Personnages correspondant au filtre &apos;{0}&apos;.
        /// </summary>
        internal static string allcharacters_header_filter {
            get {
                return ResourceManager.GetString("allcharacters_header_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le status verbeux du bot (pour vous uniquement) a été mis à {0}..
        /// </summary>
        internal static string bot_verbose {
            get {
                return ResourceManager.GetString("bot_verbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Echec de changement du status verbeux du bot : {0}..
        /// </summary>
        internal static string bot_verbose_error {
            get {
                return ResourceManager.GetString("bot_verbose_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} a été créé avec succès..
        /// </summary>
        internal static string character_created {
            get {
                return ResourceManager.GetString("character_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Echec de création du personnage: {0}..
        /// </summary>
        internal static string character_creation_failed {
            get {
                return ResourceManager.GetString("character_creation_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} n&apos;a pas pu être défini comme votre personnage par défaut : {1}..
        /// </summary>
        internal static string character_default_failed {
            get {
                return ResourceManager.GetString("character_default_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} a été défini comme votre personnage par défaut..
        /// </summary>
        internal static string character_default_set {
            get {
                return ResourceManager.GetString("character_default_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pas de personnage trouvé ayant le nom ou l&apos;alias &apos;{0}&apos;..
        /// </summary>
        internal static string character_not_found {
            get {
                return ResourceManager.GetString("character_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Echec de mise à jour du personnage: {0}..
        /// </summary>
        internal static string character_update_failed {
            get {
                return ResourceManager.GetString("character_update_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Des erreurs ont eu lieu lors de la mise à jour de {0}:\n{1}\nLe reste (le cas échéant) a été enregistré..
        /// </summary>
        internal static string character_update_incomplete {
            get {
                return ResourceManager.GetString("character_update_incomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Personnages par défaut :.
        /// </summary>
        internal static string characters_header {
            get {
                return ResourceManager.GetString("characters_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Personnages par défaut correspondant au filtre &apos;{0}&apos;.
        /// </summary>
        internal static string characters_header_filter {
            get {
                return ResourceManager.GetString("characters_header_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aide pour la commande **{0}{1}**\n\nAliases:.
        /// </summary>
        internal static string command_help {
            get {
                return ResourceManager.GetString("command_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La commande **{0}** n&apos;a pas été trouvée..
        /// </summary>
        internal static string command_not_found {
            get {
                return ResourceManager.GetString("command_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paramètres : {}: {}\n.
        /// </summary>
        internal static string command_parameters {
            get {
                return ResourceManager.GetString("command_parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Résumé : {0}\n\n.
        /// </summary>
        internal static string command_summary {
            get {
                return ResourceManager.GetString("command_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &apos;{0}&apos; est à présent MJ sur le serveur..
        /// </summary>
        internal static string gm_add {
            get {
                return ResourceManager.GetString("gm_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &apos;{0}&apos; est déjà MJ sur le serveur..
        /// </summary>
        internal static string gm_already {
            get {
                return ResourceManager.GetString("gm_already", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &apos;{0}&apos; n&apos;est pas MJ sur le serveur..
        /// </summary>
        internal static string gm_not {
            get {
                return ResourceManager.GetString("gm_not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &apos;{0}&apos; n&apos;est plus MJ sur le serveur..
        /// </summary>
        internal static string gm_removed {
            get {
                return ResourceManager.GetString("gm_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commandes disponibles pour le bot. Pour avoir plus de détails à propos de la commande *cmd*, envoyez **{0}help cmd**..
        /// </summary>
        internal static string help_header {
            get {
                return ResourceManager.GetString("help_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Echec de génération de la liste de personnages : {0}..
        /// </summary>
        internal static string list_failed {
            get {
                return ResourceManager.GetString("list_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La langue a été changée en &apos;{0}&apos;..
        /// </summary>
        internal static string local_changed {
            get {
                return ResourceManager.GetString("local_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Echec de changement de la langue en &apos;{0}&apos; : le code doit faire deux charactères..
        /// </summary>
        internal static string local_too_long {
            get {
                return ResourceManager.GetString("local_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Echec de modification du message : {0}..
        /// </summary>
        internal static string message_edit_error {
            get {
                return ResourceManager.GetString("message_edit_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Echec d&apos;envoi du message : {0}..
        /// </summary>
        internal static string message_send_error {
            get {
                return ResourceManager.GetString("message_send_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Personnages vous appartenant :.
        /// </summary>
        internal static string mycharacters_header {
            get {
                return ResourceManager.GetString("mycharacters_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Personnages vous appartenant correspondant au filtre &apos;{0}&apos;.
        /// </summary>
        internal static string mycharacters_header_filter {
            get {
                return ResourceManager.GetString("mycharacters_header_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun personnage n&apos;a été trouvé.
        /// </summary>
        internal static string no_character_found {
            get {
                return ResourceManager.GetString("no_character_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le préfixe a été défini à &apos;{0}&apos;.
        /// </summary>
        internal static string prefix_changed {
            get {
                return ResourceManager.GetString("prefix_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Echec de changement du préfix en &apos;{0}&apos; : trop de conflits possibles..
        /// </summary>
        internal static string prefix_failed {
            get {
                return ResourceManager.GetString("prefix_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à #{0} n&apos;a pas pu être défini comme votre salon privré : {1}..
        /// </summary>
        internal static string private_channel_failed {
            get {
                return ResourceManager.GetString("private_channel_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à #{0} a été défini comme votre salon privé..
        /// </summary>
        internal static string private_channel_set {
            get {
                return ResourceManager.GetString("private_channel_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &apos;{0}&apos; n&apos;a pas pu être défini à &apos;{1}&apos;..
        /// </summary>
        internal static string property_set_error {
            get {
                return ResourceManager.GetString("property_set_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commande &apos;{0}&apos; inconnue..
        /// </summary>
        internal static string unknown_command {
            get {
                return ResourceManager.GetString("unknown_command", resourceCulture);
            }
        }
    }
}
